### ISSUE TITLE
Is the BigBenchHard data part of this?

### ISSUE THREAD

**Issue by nivibilla** [sileod/tasksource#3]
Hi, 

Im planning to train a model on this data and then evaluate on BigBenchHard. Is any of the BBH data in here?

Thanks

**Comment by sileod** [comment]
Hi !
Yes it is. To exclude tasks, just do

```df=list_tasks()
df=df[df.dataset_name!='tasksource/bigbench']
```
You may also want to include MMLU
See readable tasks list here:
https://github.com/sileod/tasksource/blob/main/tasks.md

**Comment by nivibilla** [comment]
Great, thank you!
